spring:
  application:
    name: gatewey-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #匹配所有请求
            allowedOrigins: "*"
            allowedMenthods:
              - GET
              - POST
              - PUT
              - DELETE

      routes:
            # 唯一标识符
            - id: changgou_goods_route
              #用户请求需要路由到该服务
              #uri: http://localhost:18081
              #lb:使用LoadBalancerClient事项负载均衡, 后面goods是微服务名称
              uri: lb://goods
              #路由断言, 路由规则配置
              predicates:
#              - Host=cloud.itheima.com**
              - Path=/**
              filters:
              - StripPrefix=1
              #局部限流过滤器
              - name: RequestRateLimiter  #请求数限流 名称不能随便写, 使用默认的facatory
                args:
                  key-resolver: "#{@ipKeyResolver}"
                  #每秒钟允许请求的个数(1个)
                  redis-rate-limiter.replenishRate: 1
                  #允许并发有4个请求(宽限的个数)
                  redis-rate.limiter.burstCapacity: 4
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
